<?php

/**
 * @file
 * Module file for kerwa_publications.
 */

/**
 * Implements hook_cron().
 */
function kerwa_publications_cron() {
  $kerwa_last_refreshed = \Drupal::state()->get('kerwa_publications_last_refreshed', 0);
  $current_time = \Drupal::time()->getCurrentTime();
  if (($kerwa_last_refreshed + 86400) > $current_time) {
    // If refreshed less than 24h ago, do nothing.
    return;
  }
  $options = \Drupal::entityTypeManager()->getStorage('kerwa_option')->loadMultiple();
  foreach ($options as $option) {
    // Get data to fill the cache.
    \Drupal::service('kerwa_publications.cache')->refreshCache($option);
  }
  \Drupal::state()->set('kerwa_publications_last_refreshed', $current_time);
}

/**
 * Implements hook_rebuild().
 */
function kerwa_publications_rebuild() {
  $current_time = \Drupal::time()->getCurrentTime();
  $options = \Drupal::entityTypeManager()->getStorage('kerwa_option')->loadMultiple();
  foreach ($options as $option) {
    // Get data to fill the cache.
    \Drupal::service('kerwa_publications.cache')->refreshCache($option);
  }
  \Drupal::state()->set('kerwa_publications_last_refreshed', $current_time);
}
